name: Playwright Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 21

      - name: Install Dependencies
        run: npm install

      - name: Docker login
        run: docker login -u ${{secrets.DOCKERLOGINUSERNAME}} -p ${{secrets.DOCKERLOGINPASSWORD}}

      - name: Pull Docker Image
        run: docker pull triforceadi/minimal-courier-api:latest

      - name: Run Docker Container
        run: docker run -d --name minimal-courier-api:latest

      - name: Run Playwright Tests
        run: |
          # Add any additional setup steps for your tests, if needed
          npx playwright test
          
          # Cleanup: Stop and remove the Docker container
          docker stop minimal-courier-api
          docker rm minimal-courier-api