name: Playwright Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Docker login
        run: docker login -u ${{secrets.DOCKERLOGINUSERNAME}} -p ${{secrets.DOCKERLOGINPASSWORD}}

      - name: Pull Docker Image
        run: docker pull triforceadi/minimal-courier-api

      - name: Run Docker Container
        run: docker run -p 3000:3000 -d --name testContainer triforceadi/minimal-courier-api

      - name: Sleep for 3 seconds
        run: sleep 3s
        shell: bash

      - name: Run Playwright Tests
        run: npx playwright test

      - name: Stop Docker Container
        run: |
          docker stop testContainer
          docker rm testContainer